import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { FaTwitter } from 'react-icons/fa'
import { FaInstagram } from 'react-icons/fa'
import { FaFacebookF } from 'react-icons/fa'
import { FaYoutube } from 'react-icons/fa'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.socials}>
          <FaTwitter size={18} color="white" className={styles.icons} />
          <FaInstagram size={18} color="white" className={styles.icons} />
          <FaFacebookF size={18} color="white" className={styles.icons} />
          <FaYoutube size={18} color="white" className={styles.icons} />
        </div>
        <nav className={styles.nav}>
          <div className={styles.navlink}><h1>PRODUCTS</h1></div>
          <div className={styles.navlink}><h1>MERCH</h1></div>
          <div className={styles.navlink}>
            <img src="../public/NERF-LOGO.png" alt="" className={styles.brand} />
          </div>
          <div className={styles.navlink}><h1>REWARDS</h1></div>
          <div className={styles.navlink}><h1>FAQ</h1></div>
        </nav>
        <div className={styles.homepage}>
          Homepage
        </div>
      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
