import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { FaTwitter } from 'react-icons/fa'
import { FaInstagram } from 'react-icons/fa'
import { FaFacebookF } from 'react-icons/fa'
import { FaYoutube } from 'react-icons/fa'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nerf Perks are Here | Nerf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NERF-LOGO.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.socials}>
          <FaTwitter size={18} color="white" className={styles.icons} />
          <FaInstagram size={18} color="white" className={styles.icons} />
          <FaFacebookF size={18} color="white" className={styles.icons} />
          <FaYoutube size={18} color="white" className={styles.icons} />
        </div>
        <nav className={styles.nav}>
          <div className={styles.navlink}><h3>PRODUCTS</h3></div>
          <div className={styles.navlink}><h3>MERCH</h3></div>
          <div className={styles.navlink}>
            <img src="/NERF-LOGO2.png" alt="" className={styles.brand} />
          </div>
          <div className={styles.navlink}><h3>REWARDS</h3></div>
          <div className={styles.navlink}><h3>FAQ</h3></div>
        </nav>
        <div className={styles.homepageContainer}>
          <div className={styles.homepageLeft}>
            <div className={styles.homepageText}>
              <p>NERF PERKS HAVE ARRIVED</p>
              <h1>BUY NERF. <br />EARN NERF <br />PERKS POINTS.</h1>
              <p>Sign up for Nerf Perks to earn rewards and a chance to win <br />tickets to the College Football Playoff National Championship.</p>

            </div>
          </div>
          <div className={styles.homepageRight}>

            <img src="/NERF-LOGO5.png" alt="" className={styles.circleBrand} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  )
}
